#!/bin/sh

# /usr/bin/osascript -e 'tell application "Finder" to display dialog "'"${0}"'"'

up () {
    echo `dirname "$@"`
}
ME=`up "${0}"`
ME=`up "${ME}"`
open -a Google\ Chrome.app "$ME/index.html"
# /usr/bin/osascript -e 'tell application "Finder" to display dialog "'"${ME}"'"'
